//Contracts
export const SEED_CONTRACTS = "SEED_CONTRACTS"

//SIMPLE STORAGE
export const CHANGE_FIELD = "CHANGE_FIELD";
export const SUBMIT_VALUE = "SUBMIT_VALUE";
export const SEED_VALUE_RECEIPT = "SEED_VALUE_RECEIPT";

//ADMIN STUFF
export const ADMIN_FORM_HANDLECHANGE = "ADMIN_FORM_HANDLECHANGE";
export const ADMIN_FORM_SUBMIT = "ADMIN_FORM_SUBMIT";
export const MINT_NFT_SUCCESS = "MINT_NFT_SUCCESS";
export const ADMIN_FORM_HANDLECHANGE_FILE = "ADMIN_FORM_HANDLECHANGE_FILE";
export const IS_MINTING = "IS_MINTING";

//AUTHENTIFICATION
export const GET_AUTH_METAMASK = "GET_AUTH_METAMASK";
export const SEED_AUTH_METAMASK = "SEED_AUTH_METAMASK";

//USER
export const GET_USER_NFTS = "GET_USER_NFTS";
export const SEED_USER_NFTS = "SEED_USER_NFTS";
export const IMPORT_TAK_METAMASK_WALLET = "IMPORT_TAK_METAMASK_WALLET";
export const GET_TAK = "GET_TAK";
export const SEED_TAK = "SEED_TAK";
export const GET_BALANCES = "GET_BALANCES";
export const SEED_BALANCES = "SEED_BALANCES";

//BUY
export const BUY_NFT = "BUY_NFT";
export const BUY_NFT_SUCCESS = "BUY_NFT_SUCCESS";
export const USER_BOUGHT_NFT = "USER_BOUGHT_NFT";

//MARKETPLACE
export const INIT_MARKET = "MARKET_INIT";
export const IS_LOADING = "IS_LOADING";
export const SEED_MARKET = "SEED_MARKET";
export const SELECT_CURRENT = "SELECT_CURRENT";

//DASHBOARD
