//types contract


//SIMPLE STORAGE
export const CHANGE_FIELD = "CHANGE_FIELD";
export const SUBMIT_VALUE = "SUBMIT_VALUE";
export const SEED_VALUE_RECEIPT = "SEED_VALUE_RECEIPT";

//ADMIN STUFF
export const ADMIN_FORM_HANDLECHANGE = "ADMIN_FORM_HANDLECHANGE";
export const ADMIN_FORM_SUBMIT = "ADMIN_FORM_SUBMIT";
export const MINT_NFT_SUCCESS = "MINT_NFT_SUCCESS";
export const ADMIN_FORM_HANDLECHANGE_FILE = "ADMIN_FORM_HANDLECHANGE_FILE";
export const IS_MINTING = "IS_MINTING";

//AUTHENTIFICATION
export const GET_AUTH_METAMASK = "GET_AUTH_METAMASK";
export const SEED_AUTH_METAMASK = "SEED_AUTH_METAMASK";


//MARKETPLACE
export const INIT_MARKET = "MARKET_INIT";
export const SEED_MARKET = "SEED_MARKET"


//DASHBOARD


