//Contracts
export const SEED_CONTRACTS = "SEED_CONTRACTS"

//SIMPLE STORAGE
export const CHANGE_FIELD = "CHANGE_FIELD";
export const SUBMIT_VALUE = "SUBMIT_VALUE";
export const SEED_VALUE_RECEIPT = "SEED_VALUE_RECEIPT";

//ADMIN STUFF
export const ADMIN_FORM_HANDLECHANGE = "ADMIN_FORM_HANDLECHANGE";
export const ADMIN_FORM_SUBMIT = "ADMIN_FORM_SUBMIT";
export const MINT_NFT_SUCCESS = "MINT_NFT_SUCCESS";
export const ADMIN_FORM_HANDLECHANGE_FILE = "ADMIN_FORM_HANDLECHANGE_FILE";


//AUTHENTIFICATION
export const GET_AUTH_METAMASK = "GET_AUTH_METAMASK";
export const SEED_AUTH_METAMASK = "SEED_AUTH_METAMASK";

//USER
export const GET_USER_NFTS = "GET_USER_NFTS";
export const SEED_USER_NFTS = "SEED_USER_NFTS";
export const IMPORT_TAK_METAMASK_WALLET = "IMPORT_TAK_METAMASK_WALLET";
export const GET_TAK = "GET_TAK";
export const SEED_TAK = "SEED_TAK";
export const GET_BALANCES = "GET_BALANCES";
export const SEED_BALANCES = "SEED_BALANCES";
export const SWAP_ETH_TAK = "SWAP_ETH_TAK";

//MARKETPLACE
export const INIT_MARKET = "MARKET_INIT";
export const SEED_MARKET = "SEED_MARKET";
export const SELECT_CURRENT = "SELECT_CURRENT";

//BUY
export const BUY_NFT = "BUY_NFT";
export const BUY_NFT_SUCCESS = "BUY_NFT_SUCCESS";
export const USER_BOUGHT_NFT = "USER_BOUGHT_NFT";
export const UPDATE_IS_FOR_SALE = "UPDATE_IS_FOR_SALE";

//SELL
export const SELL_NFT = "SELL_NFT";
export const WITHDRAW_NFT_ON_SALE = "WITHDRAW_NFT_ON_SALE";
export const APPROVE_MARKETPLACE_TO_SELL = "APPROVE_MARKETPLACE_TO_SELL";

//DASHBOARD
export const GET_USER_STORAGE = "GET_USER_STORAGE";
export const SEED_USER_STORAGE = "SEED_USER_STORAGE";
export const INIT_NEW_USER = "INIT_NEW_USER";
export const TOGGLE_NEW_USER = "TOGGLE_NEW_USER";
export const TOGGLE_TO_WISHLIST = "TOGGLE_TO_WISHLIST";
export const IS_LOADING = "IS_LOADING";
export const SUBSCRIBE_EVENTS = "SUBSCRIBE_EVENTS";