//types contract
export const DEPLOY = "DEPLOY";
export const SEED_INSTANCE = "SEED_INSTANCE";
export const CHANGE_FIELD = "CHANGE_FIELD";
export const SUBMIT_VALUE = "SUBMIT_VALUE";
export const SEED_VALUE_RECEIPT = "SEED_VALUE_RECEIPT";

export const ADMIN_FORM_HANDLECHANGE = "ADMIN_FORM_HANDLECHANGE";
export const ADMIN_FORM_SUBMIT = "ADMIN_FORM_SUBMIT";
