name: CI

on:
  push:
    branches: [ staging ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Uses Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install NPM dependencies & Client Build
    - run: npm run install-build

    - name: Install NPM dependencies & Client Build
    - run: npm run install-truffle

    - name: Truffle Test
      run: npm run test

    - name: Push to Heroku
      run: git push heroku staging:main
