name: CI

on:
  push:
    branches: [ staging ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install and Deploy
        uses: actions/setup-node@v1
      - run: npm run install-pkg
      - run: npm run deploy-matic
      - run: npm run start
        env:
          CI: true
          DEPLOY_TARGET: staging